name: "Build"

on: [push]
jobs:
    analyze:
        name: Build (Linux)

        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                sudo apt install libusb-dev bluez libbluetooth-dev dbus libdbus-1-dev libudev-dev
            - name: Build
              run: |
                ./build-PSMoveApi.sh
                ./build.sh